apiVersion : apps/v1
kind: Deployment
metadata:
  name: dind-swarm
  labels:
    app: dind-swarm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dind-swarm
  template:
    metadata:
      labels:
        app: dind-swarm
    spec:
      containers:
        - name: dind
          image: "docker:18.05-dind"
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/lib/docker
              name: dind-swarm
      volumes:
        - name: dind-swarm
          persistentVolumeClaim:
            claimName: dind-swarm